name: build

on:
  push:
    branches:
    - main
  schedule:
  - cron:  '0 0 * * *'
env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      fail-fast: false
      matrix:
        platform:
        - linux/amd64
        - linux/arm64
        os:
        - centos-stream9
        - debian
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        file: ./${{ matrix.os }}/Dockerfile
        push: true
        platforms: ${{ matrix.platform }}
        tags: ${{ env.REGISTRY }}/corite/tor:${{ matrix.os }}
